# Setup
title:        Learnable Triangulation of Human Pose
tagline:      Karim Iskakov, Egor Burkov, Victor Lempitsky, Yury Malkov
baseurl:      "/learnable-triangulation"
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Karim Iskakov
  url:        http://saic-violet.github.io/learnable-triangulation

# Gems
gems:
  - jekyll-paginate

# Others
markdown: kramdown
